//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fast_To_let.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class AddInfo
    {
        public int add_id { get; set; }
        [DisplayName("To-let catagory")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "To-let catagory is required")]
        public string tolet_catagory { get; set; }
        [DisplayName("To-let available")]
        [Required(AllowEmptyStrings = false, ErrorMessage ="Date is required")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true,DataFormatString ="{0:dd/MM/yyyy}")]

        public Nullable<System.DateTime> tolet_available { get; set; }
        [DisplayName("Area")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Area is required")]
        public string area { get; set; }
        [DisplayName("Local Area")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Local Area is required")]

        public string local_area { get; set; }
        [DisplayName ("Road No")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Road No is required")]

        public string road_no { get; set; }
        [DisplayName("House No")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "House No is required")]
        public string house_no { get; set; }
        [DisplayName("Floor No")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Floor No  is required")]
        public string floor { get; set; }
        [DisplayName("Details")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Details  is required")]
        public string details { get; set; }
        [DisplayName("Phone")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Phone  is required")]
        [DataType(DataType.PhoneNumber)]
        public int phone { get; set; }
        [DisplayName("Facilities")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Facilities  is required")]
        public string facilities { get; set; }
        [DisplayName("Rent")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Rent  is required")]
        public string rent { get; set; }
        [DisplayName("Image")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Image  is required")]
        public string photo { get; set; }
        public Nullable<bool> IsApproved { get; set; }

        public HttpPostedFileBase Image { get; set; }
    }
}
