//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fast_To_let.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string username { get; set; }
        public string email { get; set; }
        public int phone { get; set; }
        public string gender { get; set; }
        public string password { get; set; }
        public bool IsEmailVarified_ { get; set; }
        public System.Guid ActivationCode { get; set; }
    }
}
